version: '3'
services:
  api:
    image: node:15.5.1-alpine3.12
    working_dir: /app
    tty: true
    volumes:
      - ./api:/app
    command: yarn start
    ports:
      - "3001:3000"
  front:
    image: node:15.5.1-alpine3.12
    working_dir: /app
    tty: true
    volumes:
      - ./front:/app
    command: yarn start
    ports:
      - "3000:3000"